# Manipulate .txt files
### Preps:
1. Create a data folder in the assignments folder
2. Copy the birth_life_2010.txt to the data folder
3. What is the absolute path of your birth_life_2010.txt file? 
    - Hint: `import os`
4. Look up what the os library can do for you


### Questions
1. Read birth_life_2010.txt file line by line
2. Make sure that every country name is in the same list as the Birth rate and the Life expectancy belonging to that country
    - example: [Vietnam, 1.822, 74.828243902']
    - result: [[Vietnam, 1.822, 74.828243902'], ..., ['Vanuatu, 3.869, 70.819487805]]
3. Make sure all the countries names starts from capital letters
4. Round all the numbers to 2 decimals
5. Sort the list based on the country names from A -> Z
6. Remove the last letter of every country


### Hard Questions
1. Create a function that takes a list of words and returns step 3 till 6 as a list
 - do not forget the comments and to explain what your function does and what it returns (what is the expected function output)
2. How many country does the file contain?
3. Do all countries have birth and life expectancy present? 
4. How many countries start with the letter M?
5. How many countries have a 'z' in their name

In [7]:
import os
import pandas as pd

print("Path at terminal when executing this file")
print(os.getcwd())

#import and show data
df = pd.read_csv('birth_life_2010.txt', sep = '\t')
df.head()

Path at terminal when executing this file
/Users/matlija/Documents/Pylaides/Bootcamp-Data-Analysis-beginner-apr-may2020-master/week1/homework

       Country  Birth rate  Life expectancy
0      Vietnam       1.822        74.828244
1      Vanuatu       3.869        70.819488
2        Tonga       3.911        72.150659
3  Timor-Leste       5.578        61.999854
4     Thailand       1.579        73.927659

In [43]:
# question 1
#open and read file line by line
with open('birth_life_2010.txt', 'r') as file:
    all_text = file.read()
   # print(file.readline(5))

In [ ]:
#where we split line by using \n
list_of_text = all_text.split('\n')

# for loop to read each part of string in separate string
text_list = []

for line in list_of_text:
    text_list.append(line.split('\t'))
print(text_list)

#here we are using a split function to separate one string into a list of three strings

In [30]:
for line in text_list:
    if line[0][0]

C
V
V
T
T
T
S
S
S
P
P
N
N
M
M
M
M
M
L
K
J
I
H
G
F
F
D
C
C
B
A
U
U
U
T
T
T
S
S
S
S
S
S
R
R
P
P
N
N
M
M
M
L
L
L
K
K
K
I
I
I
H
G
G
G
F
F
E
D
C
C
C
C
B
B
B
B
A
A
A
A
V
V
U
T
T
S
S
S
P
P
P
P
N
M
J
H
H
G
G
G
E
E
D
C
C
C
C
B
B
B
B
A
A
Y
W
U
T
S
S
Q
O
M
M
L
L
K
J
I
I
I
E
D
B
A
U
C
B
S
P
N
M
I
B
B
A
Z
Z
U
T
T
T
S
S
S
S
S
S
S
R
N
N
N
M
M
M
M
M
M
L
L
K
G
G
G
G
E
E
E
D
C
C
C
C
C
C
B
B
B
B
A

In [46]:
#next step is to be sure that all countries starts with capital letter

for line in text_list:
    if line[0][0] == line[0][0].upper():
        print(True)
    else:
        print(False)

True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True

In [55]:
#round values and make a new list
text_list_r = []
header_tl = text_list[0]
for line in text_list[1:]:
        st2 = round(float(line[1]),2)
        st3 = round(float(line[2]),2)
        text_list_r.append([line[0],st2,st3])
print([header_tl]+text_list_r)

[['Country', 'Birth rate', 'Life expectancy'], ['Vietnam', 1.82, 74.83], ['Vanuatu', 3.87, 70.82], ['Tonga', 3.91, 72.15], ['Timor-Leste', 5.58, 62.0], ['Thailand', 1.58, 73.93], ['Solomon Islands', 4.23, 67.47], ['Singapore', 1.15, 81.64], ['Samoa', 3.86, 72.31], ['Philippines', 3.14, 68.48], ['Papua New Guinea', 3.95, 62.44], ['New Zealand', 2.16, 80.7], ['New Caledonia', 2.14, 76.3], ['Myanmar', 2.0, 64.66], ['Mongolia', 2.5, 68.19], ['Micronesia', 3.45, 68.76], ['Malaysia', 2.63, 74.02], ['Macao SAR, China', 1.09, 80.78], ['Lao PDR', 2.75, 67.06], ['Korea', 1.22, 80.76], ['Japan', 1.39, 82.93], ['Indonesia', 2.12, 68.89], ['Hong Kong SAR, China', 1.11, 82.88], ['Guam', 2.47, 75.99], ['French Polynesia', 2.09, 75.08], ['Fiji', 2.67, 69.23], ['Dem. Rep. Korea', 2.02, 68.53], ['China', 1.6, 73.27], ['Cambodia', 2.58, 62.54], ['Brunei', 2.04, 77.93], ['Australia', 1.92, 81.7], ['Uzbekistan', 2.5, 68.0], ['United Kingdom', 1.94, 80.4], ['Ukraine', 1.45, 70.28], ['Turkmenistan', 2.4, 64.86], ['Turkey', 2.09, 73.7], ['Tajikistan', 3.3, 67.26], ['Switzerland', 1.5, 82.25], ['Sweden', 1.98, 81.45], ['Spain', 1.39, 81.63], ['Slovenia', 1.57, 79.42], ['Slovak Republic', 1.4, 75.11], ['Serbia', 1.4, 73.94], ['Russia', 1.54, 68.8], ['Romania', 1.38, 73.46], ['Portugal', 1.32, 79.03], ['Poland', 1.38, 76.25], ['Norway', 1.95, 81.0], ['Netherlands', 1.79, 80.7], ['Montenegro', 1.66, 74.31], ['Moldova', 1.48, 68.9], ['Macedonia', 1.42, 74.62], ['Luxembourg', 1.63, 80.09], ['Lithuania', 1.55, 73.27], ['Latvia', 1.17, 73.48], ['Kyrgyz Republic', 2.9, 69.37], ['Kosovo', 2.29, 69.88], ['Kazakhstan', 2.59, 68.3], ['Italy', 1.4, 81.74], ['Ireland', 2.07, 80.29], ['Iceland', 2.2, 81.45], ['Hungary', 1.25, 74.21], ['Greece', 1.44, 80.39], ['Germany', 1.39, 79.99], ['Georgia', 1.55, 73.33], ['France', 2.0, 81.37], ['Finland', 1.87, 79.87], ['Estonia', 1.63, 75.43], ['Denmark', 1.87, 79.1], ['Czech Republic', 1.49, 77.42], ['Cyprus', 1.48, 79.38], ['Croatia', 1.46, 76.48], ['Channel Islands', 1.46, 79.83], ['Bulgaria', 1.49, 73.51], ['Bosnia and Herzegovina', 1.15, 75.4], ['Belgium', 1.84, 79.94], ['Belarus', 1.44, 70.4], ['Azerbaijan', 2.3, 70.51], ['Austria', 1.44, 80.38], ['Armenia', 1.74, 73.78], ['Albania', 1.54, 76.9], ['Virgin Islands', 1.8, 79.19], ['Venezuela', 2.49, 74.13], ['Uruguay', 1.99, 76.24], ['Trinidad and Tobago', 1.64, 69.75], ['The Bahamas', 1.9, 75.22], ['Suriname', 2.34, 70.34], ['St. Vincent and the Grenadines', 2.06, 72.11], ['St. Lucia', 1.98, 74.44], ['Puerto Rico', 1.8, 78.91], ['Peru', 2.5, 73.76], ['Paraguay', 2.95, 72.28], ['Panama', 2.48, 75.97], ['Nicaragua', 2.62, 73.73], ['Mexico', 2.32, 76.68], ['Jamaica', 2.33, 72.85], ['Honduras', 3.14, 72.83], ['Haiti', 3.34, 61.76], ['Guyana', 2.26, 69.55], ['Guatemala', 3.98, 70.83], ['Grenada', 2.23, 75.66], ['El Salvador', 2.25, 71.73], ['Ecuador', 2.48, 75.46], ['Dominican Republic', 2.58, 73.2], ['Cuba', 1.47, 78.96], ['Costa Rica', 1.85, 79.19], ['Colombia', 2.1, 73.43], ['Chile', 1.86, 78.89], ['Brazil', 1.83, 73.1], ['Bolivia', 3.35, 66.27], ['Belize', 2.79, 75.84], ['Barbados', 1.55, 76.57], ['Aruba', 1.7, 74.98], ['Argentina', 2.21, 75.63], ['Yemen', 5.2, 65.03], ['West Bank and Gaza', 4.45, 72.64], ['United Arab Emirates', 1.75, 76.57], ['Tunisia', 2.04, 74.6], ['Syrian Arab Republic', 2.93, 75.7], ['Saudi Arabia', 2.81, 73.85], ['Qatar', 2.27, 78.1], ['Oman', 2.31, 73.12], ['Morocco', 2.28, 71.86], ['Malta', 1.38, 80.95], ['Libya', 2.56, 74.75], ['Lebanon', 1.8, 72.41], ['Kuwait', 2.29, 74.6], ['Jordan', 3.8, 73.29], ['Israel', 3.03, 81.5], ['Iraq', 4.7, 68.49], ['Iran', 1.67, 72.75], ['Egypt', 2.73, 72.98], ['Djibouti', 3.75, 57.53], ['Bahrain', 2.54, 75.02], ['Algeria', 2.26, 72.85], ['United States', 2.1, 78.24], ['Canada', 1.68, 80.8], ['Bermuda', 1.76, 79.29], ['Sri Lanka', 2.31, 74.72], ['Pakistan', 3.42, 65.2], ['Nepal', 2.73, 68.39], ['Maldives', 1.75, 76.55], ['India', 2.62, 65.13], ['Bhutan', 2.4, 66.91], ['Bangladesh', 2.25, 68.63], ['Afghanistan', 6.29, 48.28], ['Zimbabwe', 3.29, 49.86], ['Zambia', 6.26, 48.46], ['Uganda', 6.15, 53.61], ['Togo', 4.07, 56.59], ['The Gambia', 4.9, 58.16], ['Tanzania', 5.54, 57.39], ['Swaziland', 3.36, 48.34], ['Sudan', 4.4, 61.11], ['South Africa', 2.46, 52.08], ['Somalia', 6.34, 50.9], ['Sierra Leone', 4.98, 47.4], ['Seychelles', 2.5, 73.03], ['Senegal', 4.82, 58.95], ['Rwanda', 5.37, 55.06], ['Nigeria', 5.53, 51.41], ['Niger', 7.06, 54.27], ['Namibia', 3.22, 62.07], ['Mozambique', 4.91, 49.7], ['Mauritius', 1.47, 72.97], ['Mauritania', 4.53, 58.22], ['Mali', 6.29, 50.95], ['Malawi', 5.99, 53.46], ['Madagascar', 4.65, 66.47], ['Liberia', 5.24, 56.15], ['Lesotho', 3.2, 47.37], ['Kenya', 4.72, 56.5], ['Guinea-Bissau', 5.06, 47.7], ['Guinea', 5.25, 53.64], ['Ghana', 4.17, 63.84], ['Gabon', 3.25, 62.29], ['Ethiopia', 4.19, 58.72], ['Eritrea', 4.45, 60.99], ['Equatorial Guinea', 5.18, 50.84], ['Dem. Rep. Congo', 5.78, 48.07], ['Congo', 4.54, 56.96], ['Comoros', 4.92, 60.63], ['Chad', 5.98, 49.19], ['Central African Republic', 4.63, 47.62], ['Cape Verde', 2.4, 73.77], ['Cameroon', 4.49, 51.06], ['Burundi', 4.34, 49.88], ['Burkina Faso', 5.85, 54.92], ['Botswana', 2.75, 53.11], ['Benin', 5.29, 55.59], ['Angola', 5.44, 50.65]]

In [57]:
#test to see how it is working when I am using with open commands and use a loop inside it
#with open('birth_life_2010.txt', 'r') as file:
 #   for line in file:
  #      print(line, end='')

In [ ]:
def first(x):
    return x[0]  # lambda x : x[0]
#test
first(['a',2,1])

In [82]:
# sort the list by country names
new_text_sorted=text_list_r.sort(key=first)

In [78]:
len(text_list_r[0][0])-1

10

In [81]:
text_list_r[0][0][:-1]

'Afghanista'

In [85]:
new_text = []
for line in text_list_r[1:]:
    text=line[0][:-1]
    new_text.append([text,line[1],line[2]])
print([header_tl]+new_text)

[['Country', 'Birth rate', 'Life expectancy'], ['Albani', 1.54, 76.9], ['Algeri', 2.26, 72.85], ['Angol', 5.44, 50.65], ['Argentin', 2.21, 75.63], ['Armeni', 1.74, 73.78], ['Arub', 1.7, 74.98], ['Australi', 1.92, 81.7], ['Austri', 1.44, 80.38], ['Azerbaija', 2.3, 70.51], ['Bahrai', 2.54, 75.02], ['Banglades', 2.25, 68.63], ['Barbado', 1.55, 76.57], ['Belaru', 1.44, 70.4], ['Belgiu', 1.84, 79.94], ['Beliz', 2.79, 75.84], ['Beni', 5.29, 55.59], ['Bermud', 1.76, 79.29], ['Bhuta', 2.4, 66.91], ['Bolivi', 3.35, 66.27], ['Bosnia and Herzegovin', 1.15, 75.4], ['Botswan', 2.75, 53.11], ['Brazi', 1.83, 73.1], ['Brune', 2.04, 77.93], ['Bulgari', 1.49, 73.51], ['Burkina Fas', 5.85, 54.92], ['Burund', 4.34, 49.88], ['Cambodi', 2.58, 62.54], ['Cameroo', 4.49, 51.06], ['Canad', 1.68, 80.8], ['Cape Verd', 2.4, 73.77], ['Central African Republi', 4.63, 47.62], ['Cha', 5.98, 49.19], ['Channel Island', 1.46, 79.83], ['Chil', 1.86, 78.89], ['Chin', 1.6, 73.27], ['Colombi', 2.1, 73.43], ['Comoro', 4.92, 60.63], ['Cong', 4.54, 56.96], ['Costa Ric', 1.85, 79.19], ['Croati', 1.46, 76.48], ['Cub', 1.47, 78.96], ['Cypru', 1.48, 79.38], ['Czech Republi', 1.49, 77.42], ['Dem. Rep. Cong', 5.78, 48.07], ['Dem. Rep. Kore', 2.02, 68.53], ['Denmar', 1.87, 79.1], ['Djibout', 3.75, 57.53], ['Dominican Republi', 2.58, 73.2], ['Ecuado', 2.48, 75.46], ['Egyp', 2.73, 72.98], ['El Salvado', 2.25, 71.73], ['Equatorial Guine', 5.18, 50.84], ['Eritre', 4.45, 60.99], ['Estoni', 1.63, 75.43], ['Ethiopi', 4.19, 58.72], ['Fij', 2.67, 69.23], ['Finlan', 1.87, 79.87], ['Franc', 2.0, 81.37], ['French Polynesi', 2.09, 75.08], ['Gabo', 3.25, 62.29], ['Georgi', 1.55, 73.33], ['German', 1.39, 79.99], ['Ghan', 4.17, 63.84], ['Greec', 1.44, 80.39], ['Grenad', 2.23, 75.66], ['Gua', 2.47, 75.99], ['Guatemal', 3.98, 70.83], ['Guine', 5.25, 53.64], ['Guinea-Bissa', 5.06, 47.7], ['Guyan', 2.26, 69.55], ['Hait', 3.34, 61.76], ['Hondura', 3.14, 72.83], ['Hong Kong SAR, Chin', 1.11, 82.88], ['Hungar', 1.25, 74.21], ['Icelan', 2.2, 81.45], ['Indi', 2.62, 65.13], ['Indonesi', 2.12, 68.89], ['Ira', 1.67, 72.75], ['Ira', 4.7, 68.49], ['Irelan', 2.07, 80.29], ['Israe', 3.03, 81.5], ['Ital', 1.4, 81.74], ['Jamaic', 2.33, 72.85], ['Japa', 1.39, 82.93], ['Jorda', 3.8, 73.29], ['Kazakhsta', 2.59, 68.3], ['Keny', 4.72, 56.5], ['Kore', 1.22, 80.76], ['Kosov', 2.29, 69.88], ['Kuwai', 2.29, 74.6], ['Kyrgyz Republi', 2.9, 69.37], ['Lao PD', 2.75, 67.06], ['Latvi', 1.17, 73.48], ['Lebano', 1.8, 72.41], ['Lesoth', 3.2, 47.37], ['Liberi', 5.24, 56.15], ['Liby', 2.56, 74.75], ['Lithuani', 1.55, 73.27], ['Luxembour', 1.63, 80.09], ['Macao SAR, Chin', 1.09, 80.78], ['Macedoni', 1.42, 74.62], ['Madagasca', 4.65, 66.47], ['Malaw', 5.99, 53.46], ['Malaysi', 2.63, 74.02], ['Maldive', 1.75, 76.55], ['Mal', 6.29, 50.95], ['Malt', 1.38, 80.95], ['Mauritani', 4.53, 58.22], ['Mauritiu', 1.47, 72.97], ['Mexic', 2.32, 76.68], ['Micronesi', 3.45, 68.76], ['Moldov', 1.48, 68.9], ['Mongoli', 2.5, 68.19], ['Montenegr', 1.66, 74.31], ['Morocc', 2.28, 71.86], ['Mozambiqu', 4.91, 49.7], ['Myanma', 2.0, 64.66], ['Namibi', 3.22, 62.07], ['Nepa', 2.73, 68.39], ['Netherland', 1.79, 80.7], ['New Caledoni', 2.14, 76.3], ['New Zealan', 2.16, 80.7], ['Nicaragu', 2.62, 73.73], ['Nige', 7.06, 54.27], ['Nigeri', 5.53, 51.41], ['Norwa', 1.95, 81.0], ['Oma', 2.31, 73.12], ['Pakista', 3.42, 65.2], ['Panam', 2.48, 75.97], ['Papua New Guine', 3.95, 62.44], ['Paragua', 2.95, 72.28], ['Per', 2.5, 73.76], ['Philippine', 3.14, 68.48], ['Polan', 1.38, 76.25], ['Portuga', 1.32, 79.03], ['Puerto Ric', 1.8, 78.91], ['Qata', 2.27, 78.1], ['Romani', 1.38, 73.46], ['Russi', 1.54, 68.8], ['Rwand', 5.37, 55.06], ['Samo', 3.86, 72.31], ['Saudi Arabi', 2.81, 73.85], ['Senega', 4.82, 58.95], ['Serbi', 1.4, 73.94], ['Seychelle', 2.5, 73.03], ['Sierra Leon', 4.98, 47.4], ['Singapor', 1.15, 81.64], ['Slovak Republi', 1.4, 75.11], ['Sloveni', 1.57, 79.42], ['Solomon Island', 4.23, 67.47], ['Somali', 6.34, 50.9], ['South Afric', 2.46, 52.08], ['Spai', 1.39, 81.63], ['Sri Lank', 2.31, 74.72], ['St. Luci', 1.98, 74.44], ['St. Vincent and the Grenadine', 2.06, 72.11], ['Suda', 4.4, 61.11], ['Surinam', 2.34, 70.34], ['Swazilan', 3.36, 48.34], ['Swede', 1.98, 81.45], ['Switzerlan', 1.5, 82.25], ['Syrian Arab Republi', 2.93, 75.7], ['Tajikista', 3.3, 67.26], ['Tanzani', 5.54, 57.39], ['Thailan', 1.58, 73.93], ['The Bahama', 1.9, 75.22], ['The Gambi', 4.9, 58.16], ['Timor-Lest', 5.58, 62.0], ['Tog', 4.07, 56.59], ['Tong', 3.91, 72.15], ['Trinidad and Tobag', 1.64, 69.75], ['Tunisi', 2.04, 74.6], ['Turke', 2.09, 73.7], ['Turkmenista', 2.4, 64.86], ['Ugand', 6.15, 53.61], ['Ukrain', 1.45, 70.28], ['United Arab Emirate', 1.75, 76.57], ['United Kingdo', 1.94, 80.4], ['United State', 2.1, 78.24], ['Urugua', 1.99, 76.24], ['Uzbekista', 2.5, 68.0], ['Vanuat', 3.87, 70.82], ['Venezuel', 2.49, 74.13], ['Vietna', 1.82, 74.83], ['Virgin Island', 1.8, 79.19], ['West Bank and Gaz', 4.45, 72.64], ['Yeme', 5.2, 65.03], ['Zambi', 6.26, 48.46], ['Zimbabw', 3.29, 49.86]]

In [69]:
#text_list_r